# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    App\Repository\ZahlungRepository:
        arguments:
            $registry: '@doctrine'
            
    App\Service\Parser\ParserFactory:
        arguments:
            $projectDir: '%kernel.project_dir%'
            
    App\Service\BankStatementParsingService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # HGA Service Configuration
    App\Service\Hga\CalculationInterface:
        alias: App\Service\Hga\Calculation\DistributionService
        
    App\Service\Hga\Configuration\HgaConfiguration:
        arguments:
            $projectDir: '%kernel.project_dir%'
        
    App\Service\Hga\ConfigurationInterface:
        alias: App\Service\Hga\Configuration\HgaConfiguration
        
    App\Service\Hga\HgaServiceInterface:
        alias: App\Service\Hga\HgaService
        
    App\Service\Hga\ReportGeneratorInterface:
        alias: App\Service\Hga\Report\TxtReportGenerator

    App\Command\HgaGenerateCommand:
        arguments:
            $txtReportGenerator: '@App\Service\Hga\Report\TxtReportGenerator'
            $pdfReportGenerator: '@App\Service\Hga\Report\PdfReportGenerator'
            $projectDir: '%kernel.project_dir%'
    
    App\Controller\AbrechnungController:
        arguments:
            $txtReportGenerator: '@App\Service\Hga\Report\TxtReportGenerator'
            $pdfReportGenerator: '@App\Service\Hga\Report\PdfReportGenerator'
            
    App\Controller\CsvImportController:
        arguments:
            $projectDir: '%kernel.project_dir%'

